<?php

/**
 * Implements hook_menu().
 */
function gtk_general_menu() {
  $items['coordinators'] = array(
    'title' => 'Coordinators',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page callback' => 'gtk_general_blank_page'
  );

  $items['members'] = array(
    'title' => 'Members',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page callback' => 'gtk_general_blank_page'
  );

  $items['alumni'] = array(
    'title' => 'Alumni Members',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page callback' => 'gtk_general_blank_page'
  );

  $items['highschool-alumni'] = array(
    'title' => 'Highschool Alumni Members',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page callback' => 'gtk_general_blank_page'
  );

  $items['lecturers'] = array(
    'title' => 'Lecturers',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page callback' => 'gtk_general_blank_page'
  );

  $items['contact'] = array(
    'title' => 'Contact Us',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page callback' => 'gtk_general_blank_page'
  );

  $items['contact-success'] = array(
    'title' => 'Contact Us',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page callback' => 'gtk_general_success_page'
  );

  return $items;
}

function gtk_general_blank_page() {
  return '';
}

function gtk_general_success_page() {
  $output = '<div class="alert alert-success alert-dismissable">
<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
<h2 class="element-invisible">Status message</h2>
Your message has been sent
</div>';

  return $output;
}

function gtk_general_contact_form() {
  $form = array();
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
    '#element_validate' => array('gtk_validate_name'),
  );

  $form['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('Email Address'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
    '#element_validate' => array('gtk_validate_email'),
  );

  $form['subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#required' => TRUE,
    '#cols' => 60,
    '#resizable' => FALSE
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

  $form['#submit'] = array('gtk_general_send_contact_mail');

  return $form;
}

function gtk_validate_email($element, $form_state) {
  if (!valid_email_address($form_state['values']['mail'])) {
    form_error($element, t('Please enter valid email address'));
  }
}


function gtk_validate_name($element, $form_state) {
  $validation = preg_match('/\\d/', $form_state['values']['name']);
  if ($validation > 0) {
    form_error($element, t('Please enter valid name'));
  }
}

function gtk_general_send_contact_mail($form, &$form_state) {

  $module = 'gtk_general';
  $key = 'send_contact_mail';
  $language = language_default();
  $params = array();
  $from = NULL;
  $send = FALSE;
  $email = 'bene.lori89@gmail.com';
  $message = drupal_mail($module, $key, $email, $language, $params, $form_state['values']['mail'], $send);

  $message['subject'] = t('Somebody has sent you a contact email from the website.');
  $message['body'] = array();
  $message['body'][] = 'From: ' . check_plain($form_state['values']['mail']);
  $message['body'][] = 'Name: ' . check_plain($form_state['values']['name']);
  $message['body'][] = 'Subject: ' . check_plain($form_state['values']['subject']);
  $message['body'][] = 'Message: ' . check_plain($form_state['values']['message']);

  // Retrieve the responsible implementation for this message.
  $system = drupal_mail_system($module, $key);

  // Format the message body.
  $message = $system->format($message);

  // Send e-mail.
  $message['result'] = $system->mail($message);
  $form_state['redirect'] = 'contact-success';
}

/**
 * Implements hook_block_info().
 */
function gtk_general_block_info() {
  return array(
    'membership_application' => array(
      'info' => t('GTK Membership Application'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'support' => array(
      'info' => t('GTK Support Us'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'contact_info' => array(
      'info' => t('GTK Contact Info'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'contact_form' => array(
      'info' => t('GTK Contact Form'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'site_map' => array(
      'info' => t('Site Map'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'social_media_menu_link_block' => array(
      'info' => t('Social Media Icons'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function gtk_general_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'membership_application':

      $query = db_select('node', 'n');

      $query->join('field_data_field_image', 'i', 'n.nid = i.entity_id');
      $query->join('field_data_field_simple_pages', 's', 'n.nid = s.entity_id');

      $query ->condition('s.field_simple_pages_value', 'Application', '=');

      $query->fields('i');

      $result = $query->execute()->fetchAll();
      $url = '';
      if (!empty($result)) {
        $image = file_load($result[0]->field_image_fid);
        $url = file_create_url($image->uri);
      }
      $block['content'] = '<img src="' . $url . '"/>';

      break;

    case 'support':

      $block['content'] = l('Support Us', 'content/support-us');
      break;

    case 'contact_info':
      $block['content'] = '<ul class="tick"><li>12 Cobham Ave, Melrose Park</li>
<li>Phone: +000 123 456 789</li>
<li>Fax: +000 123 456 789</li>
<li>Email: <a href="mailto:office@yamato-marketing.com">office@yamato-marketing.com</a></li>
</ul>
<div class="social-icons"><ul class="icons-social icon-button-bg"><li><a class="fa-button" href="https://www.facebook.com/gtk.ro"><i class="fa fa-facebook"></i></a></li></ul></div>
';
      break;


    case 'contact_form':
      $block['content'] = drupal_get_form('gtk_general_contact_form');
      break;

    case 'site_map':
      $block['content'] = theme('site_map');
      break;

    case 'social_media_menu_link_block':
      $path_to_profile = drupal_get_path('profile', 'gtk');
      $output = '<ul class="social_media_menu">
        <li class="social_media_menu_link"><a href="https://www.facebook.com/gtk.ro"><img src="' . $path_to_profile . '/images/fb.jpg"></a> </li>
        <li class="social_media_menu_link"><a href="https://plus.google.com/u/0/105548417833814696884/posts"><img src="' . $path_to_profile . '/images/google-plus.jpg"></a> </li>
</ul>';
      $block['content'] = $output;
      break;
  }
  return $block;
}

function gtk_general_site_map_menu_tree_main_menu_alter(&$tree, $menu) {
  foreach ($tree as $key => $menu_links) {
    $tree[$key]['below'] = array();
  }
}
